
---
- name: Configure webserver with nginx
  hosts: webserver
  sudo: True
  tasks:
    - name: Add epel-release repo
      yum: 
        name: epel-release
        state: present
    - name: install nginx
      yum: pkg=nginx state=installed update_cache=yes
      state: latest
    - name: copy nginx config  file
      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default 

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default 
        src=/etc/nginx/sites-available/default  
        state=link 
        force=yes
        state=directory 
    - name: copy  index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
        mode=0644
    - name: restart nginx
      service: name=nginx state=restarted
  

     
